// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"fmt"
	"io"
	"strconv"
)

type Address struct {
	Street  string `json:"street"`
	ZipCode string `json:"zip_code"`
	Country string `json:"country"`
	City    string `json:"city"`
}

type AddressInput struct {
	Street  string `json:"street"`
	ZipCode string `json:"zip_code"`
	Country string `json:"country"`
	City    string `json:"city"`
}

type Admin struct {
	ID        string `json:"id"`
	Email     string `json:"email"`
	Password  string `json:"password"`
	Name      string `json:"name"`
	LastName  string `json:"last_name"`
	CreatedAt int    `json:"createdAt"`
	UpdatedAt int    `json:"updatedAt"`
}

type Alert struct {
	ID        string   `json:"id"`
	Name      string   `json:"name"`
	Sex       *string  `json:"sex,omitempty"`
	Height    *int     `json:"height,omitempty"`
	Weight    *int     `json:"weight,omitempty"`
	Symptoms  []string `json:"symptoms"`
	Comment   string   `json:"comment"`
	CreatedAt int      `json:"createdAt"`
	UpdatedAt int      `json:"updatedAt"`
}

type AnteChir struct {
	ID              string                `json:"id"`
	Name            string                `json:"name"`
	InducedSymptoms []*ChirInducedSymptom `json:"induced_symptoms,omitempty"`
	CreatedAt       int                   `json:"createdAt"`
	UpdatedAt       int                   `json:"updatedAt"`
}

type AnteDisease struct {
	ID            string   `json:"id"`
	Name          string   `json:"name"`
	Chronicity    float64  `json:"chronicity"`
	SurgeryIds    []string `json:"surgery_ids,omitempty"`
	Symptoms      []string `json:"symptoms,omitempty"`
	TreatmentIds  []string `json:"treatment_ids,omitempty"`
	StillRelevant bool     `json:"still_relevant"`
	CreatedAt     int      `json:"createdAt"`
	UpdatedAt     int      `json:"updatedAt"`
}

type AnteFamily struct {
	ID        string   `json:"id"`
	Name      string   `json:"name"`
	Disease   []string `json:"disease"`
	CreatedAt int      `json:"createdAt"`
	UpdatedAt int      `json:"updatedAt"`
}

type BlackList struct {
	ID        string   `json:"id"`
	Token     []string `json:"token"`
	CreatedAt int      `json:"createdAt"`
	UpdatedAt int      `json:"updatedAt"`
}

type Chat struct {
	ID           string              `json:"id"`
	Participants []*ChatParticipants `json:"participants"`
	Messages     []*ChatMessages     `json:"messages"`
	CreatedAt    int                 `json:"createdAt"`
	UpdatedAt    int                 `json:"updatedAt"`
}

type ChatMessages struct {
	OwnerID    string `json:"owner_id"`
	Message    string `json:"message"`
	SendedTime int    `json:"sended_time"`
}

type ChatMessagesInput struct {
	OwnerID    string `json:"owner_id"`
	Message    string `json:"message"`
	SendedTime int    `json:"sended_time"`
}

type ChatParticipants struct {
	ParticipantID string `json:"participant_id"`
	LastSeen      int    `json:"last_seen"`
}

type ChatParticipantsInput struct {
	ParticipantID string `json:"participant_id"`
	LastSeen      int    `json:"last_seen"`
}

type ChirInducedSymptom struct {
	Symptom string  `json:"symptom"`
	Factor  float64 `json:"factor"`
}

type ChirInducedSymptomInput struct {
	Symptom string  `json:"symptom"`
	Factor  float64 `json:"factor"`
}

type CreateAdminInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
	Name     string `json:"name"`
	LastName string `json:"last_name"`
}

type CreateAlertInput struct {
	Name     string   `json:"name"`
	Sex      *string  `json:"sex,omitempty"`
	Height   *int     `json:"height,omitempty"`
	Weight   *int     `json:"weight,omitempty"`
	Symptoms []string `json:"symptoms"`
	Comment  string   `json:"comment"`
}

type CreateAnteChirInput struct {
	Name            string                     `json:"name"`
	InducedSymptoms []*ChirInducedSymptomInput `json:"induced_symptoms,omitempty"`
}

type CreateAnteDiseaseInput struct {
	Name          string   `json:"name"`
	Chronicity    *float64 `json:"chronicity,omitempty"`
	SurgeryIds    []string `json:"surgery_ids,omitempty"`
	Symptoms      []string `json:"symptoms,omitempty"`
	TreatmentIds  []string `json:"treatment_ids,omitempty"`
	StillRelevant bool     `json:"still_relevant"`
}

type CreateAnteFamilyInput struct {
	Name    string   `json:"name"`
	Disease []string `json:"disease"`
}

type CreateBlackListInput struct {
	Token []string `json:"token"`
}

type CreateChatInput struct {
	Participants []*ChatParticipantsInput `json:"participants"`
	Messages     []*ChatMessagesInput     `json:"messages"`
}

type CreateDeviceConnectInput struct {
	DeviceName  string  `json:"device_name"`
	IPAddress   string  `json:"ip_address"`
	Latitude    float64 `json:"latitude"`
	Longitude   float64 `json:"longitude"`
	Date        int     `json:"date"`
	TrustDevice bool    `json:"trust_device"`
}

type CreateDiseaseInput struct {
	Code             string                 `json:"code"`
	Name             string                 `json:"name"`
	Symptoms         []string               `json:"symptoms"`
	SymptomsWeight   []*SymptomsWeightInput `json:"symptoms_weight,omitempty"`
	OverweightFactor float64                `json:"overweight_factor"`
	HeredityFactor   float64                `json:"heredity_factor"`
	Advice           *string                `json:"advice,omitempty"`
}

type CreateDoctorInput struct {
	Email     string        `json:"email"`
	Password  string        `json:"password"`
	Name      string        `json:"name"`
	Firstname string        `json:"firstname"`
	Address   *AddressInput `json:"address"`
	Status    bool          `json:"status"`
}

type CreateDocumentInput struct {
	OwnerID      string `json:"owner_id"`
	Name         string `json:"name"`
	DocumentType string `json:"document_type"`
	Category     string `json:"category"`
	IsFavorite   bool   `json:"is_favorite"`
	DownloadURL  string `json:"download_url"`
}

type CreateDoubleAuthInput struct {
	Methods       []string `json:"methods"`
	Secret        string   `json:"secret"`
	URL           string   `json:"url"`
	TrustDeviceID string   `json:"trust_device_id"`
}

type CreateMedicalFolderInput struct {
	Name                   string   `json:"name"`
	Firstname              string   `json:"firstname"`
	Birthdate              int      `json:"birthdate"`
	Sex                    string   `json:"sex"`
	Height                 int      `json:"height"`
	Weight                 int      `json:"weight"`
	PrimaryDoctorID        string   `json:"primary_doctor_id"`
	AntecedentDiseaseIds   []string `json:"antecedent_disease_ids,omitempty"`
	OnboardingStatus       string   `json:"onboarding_status"`
	FamilyMembersMedInfoID []string `json:"family_members_med_info_id"`
}

type CreateMedicineInput struct {
	Name            string   `json:"name"`
	Unit            *string  `json:"unit,omitempty"`
	TargetDiseases  []string `json:"target_diseases"`
	TreatedSymptoms []string `json:"treated_symptoms"`
	SideEffects     []string `json:"side_effects"`
}

type CreateNlpReportInput struct {
	Version         int                     `json:"version"`
	InputSymptoms   []string                `json:"input_symptoms"`
	InputSentence   string                  `json:"input_sentence"`
	Output          []*NlpReportOutputInput `json:"output"`
	ComputationTime int                     `json:"computation_time"`
}

type CreateNotificationInput struct {
	Token   string `json:"token"`
	Message string `json:"message"`
	Title   string `json:"title"`
}

type CreatePatientInput struct {
	Email               string    `json:"email"`
	Password            string    `json:"password"`
	Status              bool      `json:"status"`
	DeviceConnect       []*string `json:"device_connect,omitempty"`
	DoubleAuthMethodsID *string   `json:"double_auth_methods_id,omitempty"`
	TrustDevices        []*string `json:"trust_devices,omitempty"`
}

type CreateRdvInput struct {
	IDPatient         string            `json:"id_patient"`
	DoctorID          string            `json:"doctor_id"`
	StartDate         int               `json:"start_date"`
	EndDate           int               `json:"end_date"`
	AppointmentStatus AppointmentStatus `json:"appointment_status"`
	SessionID         string            `json:"session_id"`
}

type CreateSaveCodeInput struct {
	Code []string `json:"code"`
}

type CreateSessionInput struct {
	Diseases          []*SessionDiseasesInput `json:"diseases"`
	Symptoms          []*SessionSymptomInput  `json:"symptoms"`
	Age               int                     `json:"age"`
	Height            int                     `json:"height"`
	Weight            int                     `json:"weight"`
	Sex               string                  `json:"sex"`
	AnteChirs         []string                `json:"ante_chirs"`
	AnteDiseases      []string                `json:"ante_diseases"`
	Medicine          []string                `json:"medicine"`
	LastQuestion      string                  `json:"last_question"`
	Logs              []*LogsInput            `json:"logs"`
	HereditaryDisease []string                `json:"hereditary_disease"`
	Alerts            []string                `json:"alerts"`
}

type CreateSymptomInput struct {
	Code             string   `json:"code"`
	Name             string   `json:"name"`
	Chronic          *int     `json:"chronic,omitempty"`
	Symptom          []string `json:"symptom"`
	Advice           *string  `json:"advice,omitempty"`
	Question         string   `json:"question"`
	QuestionBasic    string   `json:"question_basic"`
	QuestionDuration string   `json:"question_duration"`
	QuestionAnte     string   `json:"question_ante"`
}

type CreateTreatmentInput struct {
	Period     []Period `json:"period"`
	Day        []Day    `json:"day"`
	Quantity   int      `json:"quantity"`
	MedicineID string   `json:"medicine_id"`
}

type CreateTreatmentsFollowUpInput struct {
	TreatmentID string   `json:"treatment_id"`
	Date        int      `json:"date"`
	Period      []Period `json:"period"`
}

type DeviceConnect struct {
	ID          string  `json:"id"`
	DeviceName  string  `json:"device_name"`
	IPAddress   string  `json:"ip_address"`
	Latitude    float64 `json:"latitude"`
	Longitude   float64 `json:"longitude"`
	Date        int     `json:"date"`
	TrustDevice bool    `json:"trust_device"`
	CreatedAt   int     `json:"createdAt"`
	UpdatedAt   int     `json:"updatedAt"`
}

type Disease struct {
	ID               string            `json:"id"`
	Code             string            `json:"code"`
	Name             string            `json:"name"`
	Symptoms         []string          `json:"symptoms"`
	SymptomsWeight   []*SymptomsWeight `json:"symptoms_weight,omitempty"`
	OverweightFactor float64           `json:"overweight_factor"`
	HeredityFactor   float64           `json:"heredity_factor"`
	Advice           *string           `json:"advice,omitempty"`
	CreatedAt        int               `json:"createdAt"`
	UpdatedAt        int               `json:"updatedAt"`
}

type Doctor struct {
	ID                  string    `json:"id"`
	Email               string    `json:"email"`
	Password            string    `json:"password"`
	Name                string    `json:"name"`
	Firstname           string    `json:"firstname"`
	Address             *Address  `json:"address"`
	RendezVousIds       []*string `json:"rendez_vous_ids,omitempty"`
	PatientIds          []*string `json:"patient_ids,omitempty"`
	ChatIds             []*string `json:"chat_ids,omitempty"`
	DoubleAuthMethodsID *string   `json:"double_auth_methods_id,omitempty"`
	DeviceConnect       []*string `json:"device_connect,omitempty"`
	TrustDevices        []*string `json:"trust_devices,omitempty"`
	Status              bool      `json:"status"`
	CreatedAt           int       `json:"createdAt"`
	UpdatedAt           int       `json:"updatedAt"`
}

type Document struct {
	ID           string       `json:"id"`
	OwnerID      string       `json:"owner_id"`
	Name         string       `json:"name"`
	DocumentType DocumentType `json:"document_type"`
	Category     Category     `json:"category"`
	IsFavorite   bool         `json:"is_favorite"`
	DownloadURL  string       `json:"download_url"`
	CreatedAt    int          `json:"createdAt"`
	UpdatedAt    int          `json:"updatedAt"`
}

type DoubleAuth struct {
	ID            string   `json:"id"`
	Methods       []string `json:"methods"`
	Secret        string   `json:"secret"`
	URL           string   `json:"url"`
	TrustDeviceID string   `json:"trust_device_id"`
	CreatedAt     int      `json:"createdAt"`
	UpdatedAt     int      `json:"updatedAt"`
}

type Logs struct {
	Question string `json:"question"`
	Answer   string `json:"answer"`
}

type LogsInput struct {
	Question string `json:"question"`
	Answer   string `json:"answer"`
}

type MedicalAntecedents struct {
	ID            string       `json:"id"`
	Name          string       `json:"name"`
	Medicines     []*Treatment `json:"medicines"`
	StillRelevant bool         `json:"still_relevant"`
	CreatedAt     int          `json:"createdAt"`
	UpdatedAt     int          `json:"updatedAt"`
}

type MedicalAntecedentsInput struct {
	Name          string            `json:"name"`
	Medicines     []*TreatmentInput `json:"medicines"`
	StillRelevant bool              `json:"still_relevant"`
}

type MedicalInfo struct {
	ID                     string           `json:"id"`
	Name                   string           `json:"name"`
	Firstname              string           `json:"firstname"`
	Birthdate              int              `json:"birthdate"`
	Sex                    Sex              `json:"sex"`
	Height                 int              `json:"height"`
	Weight                 int              `json:"weight"`
	PrimaryDoctorID        string           `json:"primary_doctor_id"`
	OnboardingStatus       OnboardingStatus `json:"onboarding_status"`
	AntecedentDiseaseIds   []string         `json:"antecedent_disease_ids"`
	FamilyMembersMedInfoID []string         `json:"family_members_med_info_id"`
	CreatedAt              int              `json:"createdAt"`
	UpdatedAt              int              `json:"updatedAt"`
}

type Medicine struct {
	ID              string       `json:"id"`
	Name            string       `json:"name"`
	Unit            MedicineUnit `json:"unit"`
	TargetDiseases  []string     `json:"target_diseases"`
	TreatedSymptoms []string     `json:"treated_symptoms"`
	SideEffects     []string     `json:"side_effects"`
	CreatedAt       int          `json:"createdAt"`
	UpdatedAt       int          `json:"updatedAt"`
}

type MedicineInput struct {
	Name            string       `json:"name"`
	Unit            MedicineUnit `json:"unit"`
	TargetDiseases  []string     `json:"target_diseases"`
	TreatedSymptoms []string     `json:"treated_symptoms"`
	SideEffects     []string     `json:"side_effects"`
}

type Mutation struct {
}

type NlpReport struct {
	ID              string             `json:"id"`
	Version         int                `json:"version"`
	InputSymptoms   []string           `json:"input_symptoms"`
	InputSentence   string             `json:"input_sentence"`
	Output          []*NlpReportOutput `json:"output"`
	ComputationTime int                `json:"computation_time"`
	CreatedAt       int                `json:"createdAt"`
	UpdatedAt       int                `json:"updatedAt"`
}

type NlpReportOutput struct {
	Symptom string `json:"symptom"`
	Present *bool  `json:"present,omitempty"`
	Days    *int   `json:"days,omitempty"`
}

type NlpReportOutputInput struct {
	Symptom string `json:"symptom"`
	Present *bool  `json:"present,omitempty"`
	Days    *int   `json:"days,omitempty"`
}

type Notification struct {
	ID        string `json:"id"`
	Token     string `json:"token"`
	Title     string `json:"title"`
	Message   string `json:"message"`
	CreatedAt int    `json:"createdAt"`
	UpdatedAt int    `json:"updatedAt"`
}

type Options struct {
	Sort   *SortingOptions `json:"sort"`
	Limit  int             `json:"limit"`
	Offset int             `json:"offset"`
}

type Patient struct {
	ID                   string    `json:"id"`
	Email                string    `json:"email"`
	Password             string    `json:"password"`
	RendezVousIds        []*string `json:"rendez_vous_ids,omitempty"`
	MedicalInfoID        *string   `json:"medical_info_id,omitempty"`
	DocumentIds          []*string `json:"document_ids,omitempty"`
	TreatmentFollowUpIds []*string `json:"treatment_follow_up_ids,omitempty"`
	ChatIds              []*string `json:"chat_ids,omitempty"`
	DoubleAuthMethodsID  *string   `json:"double_auth_methods_id,omitempty"`
	DeviceConnect        []*string `json:"device_connect,omitempty"`
	TrustDevices         []*string `json:"trust_devices,omitempty"`
	Status               bool      `json:"status"`
	CreatedAt            int       `json:"createdAt"`
	UpdatedAt            int       `json:"updatedAt"`
}

type Query struct {
}

type Rdv struct {
	ID                string            `json:"id"`
	DoctorID          string            `json:"doctor_id"`
	IDPatient         string            `json:"id_patient"`
	StartDate         int               `json:"start_date"`
	EndDate           int               `json:"end_date"`
	CancelationReason *string           `json:"cancelation_reason,omitempty"`
	AppointmentStatus AppointmentStatus `json:"appointment_status"`
	SessionID         string            `json:"session_id"`
	HealthMethod      *string           `json:"health_method,omitempty"`
	CreatedAt         int               `json:"createdAt"`
	UpdatedAt         int               `json:"updatedAt"`
}

type SaveCode struct {
	ID        string   `json:"id"`
	Code      []string `json:"code"`
	CreatedAt int      `json:"createdAt"`
	UpdatedAt int      `json:"updatedAt"`
}

type Session struct {
	ID                string             `json:"id"`
	Diseases          []*SessionDiseases `json:"diseases"`
	Symptoms          []*SessionSymptom  `json:"symptoms"`
	Age               int                `json:"age"`
	Height            int                `json:"height"`
	Weight            int                `json:"weight"`
	Sex               string             `json:"sex"`
	AnteChirs         []string           `json:"ante_chirs"`
	AnteDiseases      []string           `json:"ante_diseases"`
	Medicine          []string           `json:"medicine"`
	LastQuestion      string             `json:"last_question"`
	Logs              []*Logs            `json:"logs"`
	HereditaryDisease []string           `json:"hereditary_disease"`
	Alerts            []string           `json:"alerts"`
	CreatedAt         int                `json:"createdAt"`
	UpdatedAt         int                `json:"updatedAt"`
}

type SessionDiseases struct {
	Name     string  `json:"name"`
	Presence float64 `json:"presence"`
}

type SessionDiseasesInput struct {
	Name            string  `json:"name"`
	Presence        float64 `json:"presence"`
	UnknownPresence float64 `json:"unknown_presence"`
}

type SessionSymptom struct {
	Name     string   `json:"name"`
	Presence int      `json:"presence"`
	Duration *int     `json:"duration,omitempty"`
	Treated  []string `json:"treated,omitempty"`
}

type SessionSymptomInput struct {
	Name     string   `json:"name"`
	Presence int      `json:"presence"`
	Duration *int     `json:"duration,omitempty"`
	Treated  []string `json:"treated,omitempty"`
}

type SortingOptions struct {
	Order SortOrder `json:"order"`
	Key   string    `json:"key"`
}

type Symptom struct {
	ID               string   `json:"id"`
	Code             string   `json:"code"`
	Name             string   `json:"name"`
	Chronic          *int     `json:"chronic,omitempty"`
	Symptom          []string `json:"symptom"`
	Advice           *string  `json:"advice,omitempty"`
	Question         string   `json:"question"`
	QuestionBasic    string   `json:"question_basic"`
	QuestionDuration string   `json:"question_duration"`
	QuestionAnte     string   `json:"question_ante"`
	CreatedAt        int      `json:"createdAt"`
	UpdatedAt        int      `json:"updatedAt"`
}

type SymptomsWeight struct {
	Symptom string  `json:"symptom"`
	Value   float64 `json:"value"`
	Chronic bool    `json:"chronic"`
}

type SymptomsWeightInput struct {
	Symptom string  `json:"symptom"`
	Value   float64 `json:"value"`
	Chronic bool    `json:"chronic"`
}

type Treatment struct {
	ID         string   `json:"id"`
	Period     []Period `json:"period"`
	Day        []Day    `json:"day"`
	Quantity   int      `json:"quantity"`
	MedicineID string   `json:"medicine_id"`
	CreatedAt  int      `json:"createdAt"`
	UpdatedAt  int      `json:"updatedAt"`
}

type TreatmentInput struct {
	Period     []*Period `json:"period"`
	Day        []*Day    `json:"day"`
	Quantity   int       `json:"quantity"`
	MedicineID string    `json:"medicine_id"`
}

type TreatmentsFollowUp struct {
	ID          string   `json:"id"`
	TreatmentID string   `json:"treatment_id"`
	Date        int      `json:"date"`
	Period      []Period `json:"period"`
	CreatedAt   int      `json:"createdAt"`
	UpdatedAt   int      `json:"updatedAt"`
}

type UpdateAdminInput struct {
	Email    *string `json:"email,omitempty"`
	Password *string `json:"password,omitempty"`
	Name     *string `json:"name,omitempty"`
	LastName *string `json:"last_name,omitempty"`
}

type UpdateAlertInput struct {
	Name     *string  `json:"name,omitempty"`
	Sex      *string  `json:"sex,omitempty"`
	Height   *int     `json:"height,omitempty"`
	Weight   *int     `json:"weight,omitempty"`
	Symptoms []string `json:"symptoms,omitempty"`
	Comment  *string  `json:"comment,omitempty"`
}

type UpdateAnteChirInput struct {
	Name            *string                    `json:"name,omitempty"`
	InducedSymptoms []*ChirInducedSymptomInput `json:"induced_symptoms,omitempty"`
}

type UpdateAnteDiseaseInput struct {
	Name          *string  `json:"name,omitempty"`
	Chronicity    *float64 `json:"chronicity,omitempty"`
	SurgeryIds    []string `json:"surgery_ids,omitempty"`
	Symptoms      []string `json:"symptoms,omitempty"`
	TreatmentIds  []string `json:"treatment_ids,omitempty"`
	StillRelevant *bool    `json:"still_relevant,omitempty"`
}

type UpdateAnteFamilyInput struct {
	Name    *string  `json:"name,omitempty"`
	Disease []string `json:"disease,omitempty"`
}

type UpdateBlackListInput struct {
	Token []string `json:"token,omitempty"`
}

type UpdateChatInput struct {
	Participants []*ChatParticipantsInput `json:"participants,omitempty"`
	Messages     []*ChatMessagesInput     `json:"messages,omitempty"`
}

type UpdateDeviceConnectInput struct {
	DeviceName  *string  `json:"device_name,omitempty"`
	IPAddress   *string  `json:"ip_address,omitempty"`
	Latitude    *float64 `json:"latitude,omitempty"`
	Longitude   *float64 `json:"longitude,omitempty"`
	Date        *int     `json:"date,omitempty"`
	TrustDevice *bool    `json:"trust_device,omitempty"`
}

type UpdateDiseaseInput struct {
	Code             *string                `json:"code,omitempty"`
	Name             *string                `json:"name,omitempty"`
	Symptoms         []string               `json:"symptoms,omitempty"`
	SymptomsWeight   []*SymptomsWeightInput `json:"symptoms_weight,omitempty"`
	OverweightFactor *float64               `json:"overweight_factor,omitempty"`
	HeredityFactor   *float64               `json:"heredity_factor,omitempty"`
	Advice           *string                `json:"advice,omitempty"`
}

type UpdateDoctorInput struct {
	Email               *string       `json:"email,omitempty"`
	Password            *string       `json:"password,omitempty"`
	Name                *string       `json:"name,omitempty"`
	Firstname           *string       `json:"firstname,omitempty"`
	RendezVousIds       []*string     `json:"rendez_vous_ids,omitempty"`
	PatientIds          []*string     `json:"patient_ids,omitempty"`
	Address             *AddressInput `json:"address,omitempty"`
	ChatIds             []*string     `json:"chat_ids,omitempty"`
	DeviceConnect       []*string     `json:"device_connect,omitempty"`
	DoubleAuthMethodsID *string       `json:"double_auth_methods_id,omitempty"`
	TrustDevices        []*string     `json:"trust_devices,omitempty"`
	Status              *bool         `json:"status,omitempty"`
}

type UpdateDocumentInput struct {
	Name       *string `json:"name,omitempty"`
	IsFavorite *bool   `json:"is_favorite,omitempty"`
}

type UpdateDoubleAuthInput struct {
	Methods       []string `json:"methods,omitempty"`
	Secret        *string  `json:"secret,omitempty"`
	URL           *string  `json:"url,omitempty"`
	TrustDeviceID *string  `json:"trust_device_id,omitempty"`
}

type UpdateMedicalFolderInput struct {
	Name                   *string           `json:"name,omitempty"`
	Firstname              *string           `json:"firstname,omitempty"`
	Birthdate              *int              `json:"birthdate,omitempty"`
	Sex                    *string           `json:"sex,omitempty"`
	Height                 *int              `json:"height,omitempty"`
	Weight                 *int              `json:"weight,omitempty"`
	PrimaryDoctorID        *string           `json:"primary_doctor_id,omitempty"`
	AntecedentDiseaseIds   []string          `json:"antecedent_disease_ids,omitempty"`
	OnboardingStatus       *OnboardingStatus `json:"onboarding_status,omitempty"`
	FamilyMembersMedInfoID []string          `json:"family_members_med_info_id,omitempty"`
}

type UpdateNotificationInput struct {
	Token   string `json:"token"`
	Message string `json:"message"`
	Title   string `json:"title"`
}

type UpdatePatientInput struct {
	Email                *string   `json:"email,omitempty"`
	Password             *string   `json:"password,omitempty"`
	MedicalInfoID        *string   `json:"medical_info_id,omitempty"`
	RendezVousIds        []*string `json:"rendez_vous_ids,omitempty"`
	DocumentIds          []*string `json:"document_ids,omitempty"`
	TreatmentFollowUpIds []*string `json:"treatment_follow_up_ids,omitempty"`
	ChatIds              []*string `json:"chat_ids,omitempty"`
}

type UpdateRdvInput struct {
	IDPatient         *string            `json:"id_patient,omitempty"`
	DoctorID          *string            `json:"doctor_id,omitempty"`
	StartDate         *int               `json:"start_date,omitempty"`
	EndDate           *int               `json:"end_date,omitempty"`
	CancelationReason *string            `json:"cancelation_reason,omitempty"`
	AppointmentStatus *AppointmentStatus `json:"appointment_status,omitempty"`
	SessionID         *string            `json:"session_id,omitempty"`
	HealthMethod      *string            `json:"health_method,omitempty"`
}

type UpdateSaveCodeInput struct {
	Code []string `json:"code,omitempty"`
}

type UpdateSessionInput struct {
	ID                string                  `json:"id"`
	Diseases          []*SessionDiseasesInput `json:"diseases,omitempty"`
	Symptoms          []*SessionSymptomInput  `json:"symptoms,omitempty"`
	Age               *int                    `json:"age,omitempty"`
	Height            *int                    `json:"height,omitempty"`
	Weight            *int                    `json:"weight,omitempty"`
	Sex               *string                 `json:"sex,omitempty"`
	AnteChirs         []string                `json:"ante_chirs,omitempty"`
	AnteDiseases      []string                `json:"ante_diseases,omitempty"`
	Medicine          []string                `json:"medicine,omitempty"`
	LastQuestion      *string                 `json:"last_question,omitempty"`
	Logs              []*LogsInput            `json:"logs,omitempty"`
	HereditaryDisease []string                `json:"hereditary_disease,omitempty"`
	Alerts            []string                `json:"alerts,omitempty"`
}

type UpdateSymptomInput struct {
	Code             *string  `json:"code,omitempty"`
	Name             *string  `json:"name,omitempty"`
	Chronic          *int     `json:"chronic,omitempty"`
	Symptom          []string `json:"symptom,omitempty"`
	Advice           *string  `json:"advice,omitempty"`
	Question         *string  `json:"question,omitempty"`
	QuestionBasic    *string  `json:"question_basic,omitempty"`
	QuestionDuration *string  `json:"question_duration,omitempty"`
	QuestionAnte     *string  `json:"question_ante,omitempty"`
}

type UpdateTreatmentInput struct {
	Period     []Period `json:"period,omitempty"`
	Day        []Day    `json:"day,omitempty"`
	Quantity   *int     `json:"quantity,omitempty"`
	MedicineID *string  `json:"medicine_id,omitempty"`
}

type UpdateTreatmentsFollowUpInput struct {
	TreatmentID *string  `json:"treatment_id,omitempty"`
	Date        *int     `json:"date,omitempty"`
	Period      []Period `json:"period,omitempty"`
}

type AppointmentStatus string

const (
	AppointmentStatusWaitingForReview    AppointmentStatus = "WAITING_FOR_REVIEW"
	AppointmentStatusAcceptedDueToReview AppointmentStatus = "ACCEPTED_DUE_TO_REVIEW"
	AppointmentStatusCanceledDueToReview AppointmentStatus = "CANCELED_DUE_TO_REVIEW"
	AppointmentStatusCanceled            AppointmentStatus = "CANCELED"
	AppointmentStatusOpened              AppointmentStatus = "OPENED"
)

var AllAppointmentStatus = []AppointmentStatus{
	AppointmentStatusWaitingForReview,
	AppointmentStatusAcceptedDueToReview,
	AppointmentStatusCanceledDueToReview,
	AppointmentStatusCanceled,
	AppointmentStatusOpened,
}

func (e AppointmentStatus) IsValid() bool {
	switch e {
	case AppointmentStatusWaitingForReview, AppointmentStatusAcceptedDueToReview, AppointmentStatusCanceledDueToReview, AppointmentStatusCanceled, AppointmentStatusOpened:
		return true
	}
	return false
}

func (e AppointmentStatus) String() string {
	return string(e)
}

func (e *AppointmentStatus) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AppointmentStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AppointmentStatus", str)
	}
	return nil
}

func (e AppointmentStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type Category string

const (
	CategoryGeneral Category = "GENERAL"
	CategoryFinance Category = "FINANCE"
)

var AllCategory = []Category{
	CategoryGeneral,
	CategoryFinance,
}

func (e Category) IsValid() bool {
	switch e {
	case CategoryGeneral, CategoryFinance:
		return true
	}
	return false
}

func (e Category) String() string {
	return string(e)
}

func (e *Category) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Category(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Category", str)
	}
	return nil
}

func (e Category) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type Day string

const (
	DayMonday    Day = "MONDAY"
	DayTuesday   Day = "TUESDAY"
	DayWednesday Day = "WEDNESDAY"
	DayThursday  Day = "THURSDAY"
	DayFriday    Day = "FRIDAY"
	DaySaturday  Day = "SATURDAY"
	DaySunday    Day = "SUNDAY"
)

var AllDay = []Day{
	DayMonday,
	DayTuesday,
	DayWednesday,
	DayThursday,
	DayFriday,
	DaySaturday,
	DaySunday,
}

func (e Day) IsValid() bool {
	switch e {
	case DayMonday, DayTuesday, DayWednesday, DayThursday, DayFriday, DaySaturday, DaySunday:
		return true
	}
	return false
}

func (e Day) String() string {
	return string(e)
}

func (e *Day) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Day(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Day", str)
	}
	return nil
}

func (e Day) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type DocumentType string

const (
	DocumentTypeXray         DocumentType = "XRAY"
	DocumentTypePrescription DocumentType = "PRESCRIPTION"
	DocumentTypeOther        DocumentType = "OTHER"
	DocumentTypeCertificate  DocumentType = "CERTIFICATE"
)

var AllDocumentType = []DocumentType{
	DocumentTypeXray,
	DocumentTypePrescription,
	DocumentTypeOther,
	DocumentTypeCertificate,
}

func (e DocumentType) IsValid() bool {
	switch e {
	case DocumentTypeXray, DocumentTypePrescription, DocumentTypeOther, DocumentTypeCertificate:
		return true
	}
	return false
}

func (e DocumentType) String() string {
	return string(e)
}

func (e *DocumentType) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = DocumentType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid DocumentType", str)
	}
	return nil
}

func (e DocumentType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type MedicineUnit string

const (
	MedicineUnitApplication MedicineUnit = "APPLICATION"
	MedicineUnitTablet      MedicineUnit = "TABLET"
	MedicineUnitTablespoon  MedicineUnit = "TABLESPOON"
	MedicineUnitCoffeespoon MedicineUnit = "COFFEESPOON"
)

var AllMedicineUnit = []MedicineUnit{
	MedicineUnitApplication,
	MedicineUnitTablet,
	MedicineUnitTablespoon,
	MedicineUnitCoffeespoon,
}

func (e MedicineUnit) IsValid() bool {
	switch e {
	case MedicineUnitApplication, MedicineUnitTablet, MedicineUnitTablespoon, MedicineUnitCoffeespoon:
		return true
	}
	return false
}

func (e MedicineUnit) String() string {
	return string(e)
}

func (e *MedicineUnit) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = MedicineUnit(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid MedicineUnit", str)
	}
	return nil
}

func (e MedicineUnit) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type OnboardingStatus string

const (
	OnboardingStatusNotStarted OnboardingStatus = "NOT_STARTED"
	OnboardingStatusInProgress OnboardingStatus = "IN_PROGRESS"
	OnboardingStatusDone       OnboardingStatus = "DONE"
)

var AllOnboardingStatus = []OnboardingStatus{
	OnboardingStatusNotStarted,
	OnboardingStatusInProgress,
	OnboardingStatusDone,
}

func (e OnboardingStatus) IsValid() bool {
	switch e {
	case OnboardingStatusNotStarted, OnboardingStatusInProgress, OnboardingStatusDone:
		return true
	}
	return false
}

func (e OnboardingStatus) String() string {
	return string(e)
}

func (e *OnboardingStatus) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = OnboardingStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid OnboardingStatus", str)
	}
	return nil
}

func (e OnboardingStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type Period string

const (
	PeriodMorning Period = "MORNING"
	PeriodNoon    Period = "NOON"
	PeriodEvening Period = "EVENING"
	PeriodNight   Period = "NIGHT"
)

var AllPeriod = []Period{
	PeriodMorning,
	PeriodNoon,
	PeriodEvening,
	PeriodNight,
}

func (e Period) IsValid() bool {
	switch e {
	case PeriodMorning, PeriodNoon, PeriodEvening, PeriodNight:
		return true
	}
	return false
}

func (e Period) String() string {
	return string(e)
}

func (e *Period) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Period(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Period", str)
	}
	return nil
}

func (e Period) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type Sex string

const (
	SexMale   Sex = "MALE"
	SexFemale Sex = "FEMALE"
	SexOther  Sex = "OTHER"
)

var AllSex = []Sex{
	SexMale,
	SexFemale,
	SexOther,
}

func (e Sex) IsValid() bool {
	switch e {
	case SexMale, SexFemale, SexOther:
		return true
	}
	return false
}

func (e Sex) String() string {
	return string(e)
}

func (e *Sex) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Sex(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Sex", str)
	}
	return nil
}

func (e Sex) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type SortOrder string

const (
	SortOrderAsc  SortOrder = "ASC"
	SortOrderDesc SortOrder = "DESC"
)

var AllSortOrder = []SortOrder{
	SortOrderAsc,
	SortOrderDesc,
}

func (e SortOrder) IsValid() bool {
	switch e {
	case SortOrderAsc, SortOrderDesc:
		return true
	}
	return false
}

func (e SortOrder) String() string {
	return string(e)
}

func (e *SortOrder) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SortOrder(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SortOrder", str)
	}
	return nil
}

func (e SortOrder) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
