// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"fmt"
	"io"
	"strconv"
)

type Admin struct {
	ID       string `json:"id"`
	Email    string `json:"email"`
	Password string `json:"password"`
	Name     string `json:"name"`
	LastName string `json:"lastName"`
}

type Alert struct {
	ID       string   `json:"id"`
	Name     string   `json:"name"`
	Sex      *string  `json:"sex,omitempty"`
	Height   *int     `json:"height,omitempty"`
	Weight   *int     `json:"weight,omitempty"`
	Symptoms []string `json:"symptoms"`
	Comment  string   `json:"comment"`
}

type AnteChir struct {
	ID              string   `json:"id"`
	Name            string   `json:"name"`
	Localisation    string   `json:"localisation"`
	InducedSymptoms []string `json:"induced_symptoms,omitempty"`
}

type AnteDisease struct {
	ID         string   `json:"id"`
	Name       string   `json:"name"`
	Chronicity float64  `json:"chronicity"`
	Chir       *string  `json:"chir,omitempty"`
	Treatment  []string `json:"treatment,omitempty"`
	Symptoms   []string `json:"symptoms,omitempty"`
}

type AnteFamily struct {
	ID      string   `json:"id"`
	Name    string   `json:"name"`
	Disease []string `json:"disease"`
}

type DemoAccount struct {
	ID       string `json:"id"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Disease struct {
	ID               string           `json:"id"`
	Code             string           `json:"code"`
	Name             string           `json:"name"`
	Symptoms         []string         `json:"symptoms"`
	SymptomsAcute    []*SymptomWeight `json:"symptoms_acute,omitempty"`
	SymptomsSubacute []*SymptomWeight `json:"symptoms_subacute,omitempty"`
	SymptomsChronic  []*SymptomWeight `json:"symptoms_chronic,omitempty"`
	Advice           *string          `json:"advice,omitempty"`
}

type Doctor struct {
	ID            string    `json:"id"`
	Email         string    `json:"email"`
	Password      string    `json:"password"`
	RendezVousIds []*string `json:"rendez_vous_ids,omitempty"`
	PatientIds    []*string `json:"patient_ids,omitempty"`
}

type Document struct {
	ID           string       `json:"id"`
	OwnerID      string       `json:"owner_id"`
	Name         string       `json:"name"`
	DocumentType DocumentType `json:"document_type"`
	Category     Category     `json:"category"`
	IsFavorite   bool         `json:"is_favorite"`
	DownloadURL  string       `json:"download_url"`
}

type Health struct {
	ID                    string   `json:"id"`
	PatientsAllergies     []string `json:"patients_allergies,omitempty"`
	PatientsIllness       []string `json:"patients_illness,omitempty"`
	PatientsTreatments    []string `json:"patients_treatments,omitempty"`
	PatientsPrimaryDoctor string   `json:"patients_primary_doctor"`
}

type Info struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	Birthdate string `json:"birthdate"`
	Height    int    `json:"height"`
	Weight    int    `json:"weight"`
	Sex       Sex    `json:"sex"`
	Surname   string `json:"surname"`
}

type Logs struct {
	Question string `json:"question"`
	Answer   string `json:"answer"`
}

type LogsInput struct {
	Question string `json:"question"`
	Answer   string `json:"answer"`
}

type MedicalInfo struct {
	Info   *string `json:"Info,omitempty"`
	Health *string `json:"Health,omitempty"`
}

type Mutation struct {
}

type Notification struct {
	ID      string `json:"id"`
	Token   string `json:"token"`
	Title   string `json:"title"`
	Message string `json:"message"`
}

type Patient struct {
	ID                 string    `json:"id"`
	Email              string    `json:"email"`
	Password           string    `json:"password"`
	RendezVousIds      []*string `json:"rendez_vous_ids,omitempty"`
	OnboardingInfoID   *string   `json:"onboarding_info_id,omitempty"`
	OnboardingHealthID *string   `json:"onboarding_health_id,omitempty"`
	DocumentIds        []*string `json:"document_ids,omitempty"`
}

type Query struct {
}

type Rdv struct {
	ID                string  `json:"id"`
	DoctorID          string  `json:"doctor_id"`
	IDPatient         string  `json:"id_patient"`
	StartDate         int     `json:"start_date"`
	EndDate           int     `json:"end_date"`
	CancelationReason *string `json:"cancelation_reason,omitempty"`
}

type Session struct {
	ID           string   `json:"id"`
	Symptoms     []string `json:"symptoms"`
	Age          int      `json:"age"`
	Height       int      `json:"height"`
	Weight       int      `json:"weight"`
	Sex          string   `json:"sex"`
	LastQuestion string   `json:"last_question"`
	Logs         []*Logs  `json:"logs"`
	Alerts       []string `json:"alerts"`
}

type Symptom struct {
	ID       string   `json:"id"`
	Code     string   `json:"code"`
	Name     string   `json:"name"`
	Location *string  `json:"location,omitempty"`
	Duration *int     `json:"duration,omitempty"`
	Acute    *int     `json:"acute,omitempty"`
	Subacute *int     `json:"subacute,omitempty"`
	Chronic  *int     `json:"chronic,omitempty"`
	Symptom  []string `json:"symptom"`
	Advice   *string  `json:"advice,omitempty"`
	Question string   `json:"question"`
}

type SymptomWeight struct {
	Key   string  `json:"key"`
	Value float64 `json:"value"`
}

type SymptomWeightInput struct {
	Key   string  `json:"key"`
	Value float64 `json:"value"`
}

type TestAccount struct {
	ID       string `json:"id"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Treatment struct {
	ID          string   `json:"id"`
	Name        string   `json:"name"`
	Disease     string   `json:"disease"`
	Symptoms    []string `json:"symptoms,omitempty"`
	SideEffects []string `json:"side_effects,omitempty"`
}

type Category string

const (
	CategoryGeneral Category = "GENERAL"
	CategoryFinance Category = "FINANCE"
)

var AllCategory = []Category{
	CategoryGeneral,
	CategoryFinance,
}

func (e Category) IsValid() bool {
	switch e {
	case CategoryGeneral, CategoryFinance:
		return true
	}
	return false
}

func (e Category) String() string {
	return string(e)
}

func (e *Category) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Category(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Category", str)
	}
	return nil
}

func (e Category) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type DocumentType string

const (
	DocumentTypeXray         DocumentType = "XRAY"
	DocumentTypePrescription DocumentType = "PRESCRIPTION"
	DocumentTypeOther        DocumentType = "OTHER"
	DocumentTypeCertificate  DocumentType = "CERTIFICATE"
)

var AllDocumentType = []DocumentType{
	DocumentTypeXray,
	DocumentTypePrescription,
	DocumentTypeOther,
	DocumentTypeCertificate,
}

func (e DocumentType) IsValid() bool {
	switch e {
	case DocumentTypeXray, DocumentTypePrescription, DocumentTypeOther, DocumentTypeCertificate:
		return true
	}
	return false
}

func (e DocumentType) String() string {
	return string(e)
}

func (e *DocumentType) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = DocumentType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid DocumentType", str)
	}
	return nil
}

func (e DocumentType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type OnboardingStatus string

const (
	OnboardingStatusNotStarted OnboardingStatus = "NOT_STARTED"
	OnboardingStatusStarted    OnboardingStatus = "STARTED"
	OnboardingStatusFinished   OnboardingStatus = "FINISHED"
)

var AllOnboardingStatus = []OnboardingStatus{
	OnboardingStatusNotStarted,
	OnboardingStatusStarted,
	OnboardingStatusFinished,
}

func (e OnboardingStatus) IsValid() bool {
	switch e {
	case OnboardingStatusNotStarted, OnboardingStatusStarted, OnboardingStatusFinished:
		return true
	}
	return false
}

func (e OnboardingStatus) String() string {
	return string(e)
}

func (e *OnboardingStatus) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = OnboardingStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid OnboardingStatus", str)
	}
	return nil
}

func (e OnboardingStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type Sex string

const (
	SexMale   Sex = "MALE"
	SexFemale Sex = "FEMALE"
	SexOther  Sex = "OTHER"
)

var AllSex = []Sex{
	SexMale,
	SexFemale,
	SexOther,
}

func (e Sex) IsValid() bool {
	switch e {
	case SexMale, SexFemale, SexOther:
		return true
	}
	return false
}

func (e Sex) String() string {
	return string(e)
}

func (e *Sex) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Sex(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Sex", str)
	}
	return nil
}

func (e Sex) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
